import { Props } from "../screens/home/ListCard";

export const listCardArticlesSearchResultsDummyData: Props = {
    title: 'Nega i Higijena',
    subTitle: '8 Rezultata',
    items: [
        {id:6, title:'Bebina koža – u čemu je razlika ?', type:'article', bodyHtml:`<b>Adipisicing</b> in nulla cillum ex amet minim anim ad sit ut duis. Non reprehenderit proident magna mollit do fugiat excepteur tempor in minim nulla incididunt reprehenderit magna. Eiusmod aliqua exercitation non irure tempor.`},
        {id:11, title:'Koliko često treba kupati bebu?', type:'article', bodyHtml:`<b>Fugiat</b> id nulla deserunt nisi velit ea ut tempor fugiat reprehenderit culpa non nisi. Incididunt laboris officia laboris et exercitation ex deserunt ullamco. Ex pariatur dolore nulla elit occaecat laborum dolore irure irure cupidatat ea non non qui. Aliquip ipsum veniam enim ut mollit non aliquip non. Amet adipisicing minim commodo ex fugiat sit id elit fugiat voluptate consectetur.`},
        {id:16, title:'Da li je bolje kupati bebu uveče ili ujutru?', type:'article', bodyHtml:`<b>Occaecat</b> sunt velit dolor dolor duis consequat officia eiusmod sint. Deserunt adipisicing exercitation eu minim mollit nulla adipisicing ad velit. Esse occaecat Lorem tempor id irure ullamco ad irure dolore duis velit quis fugiat commodo. Laboris laboris aliquip eu aliqua non minim aute veniam. Et consectetur deserunt exercitation aliquip consectetur veniam.`},
        {id:46, title:'Da li je prebrisavanje pelenom ili sunđerom dovoljno?', type:'article', bodyHtml:`<b>Velit</b> pariatur reprehenderit aliqua anim eu quis voluptate laboris ipsum. Aliqua pariatur elit irure cupidatat cillum incididunt ea minim nostrud non aliqua. Quis do officia labore ipsum laborum. Cillum laboris et proident commodo velit laboris labore et nulla culpa. Magna enim dolore duis fugiat. Do id aute ex sint aliquip dolor et.`},
        {id:26, title:'Postoji li idealna temperatura za kupanje?', type:'article', bodyHtml:`<b>Esse</b> culpa minim mollit laborum. Aute enim eiusmod laborum ex sunt laborum veniam dolor nisi est. Id incididunt fugiat magna sint ea amet. Ad fugiat cupidatat sunt enim enim excepteur deserunt pariatur ex pariatur minim deserunt nulla velit.`},
        {id:31, title:'Kada najranije možemo da kupamo bebu u ležećem položaju u kadici?', type:'article', bodyHtml:`<b>Quis</b> id eu nulla anim exercitation aute nisi. Duis aliquip qui enim reprehenderit do qui nulla ad consequat sint enim. Proident commodo occaecat voluptate proident ex cupidatat deserunt esse adipisicing qui. Minim do deserunt non enim consequat tempor aliquip labore qui amet sunt. Ea nisi proident incididunt velit.`},
        {id:36, title:'Koliko dugo beba sme da se kupa u kadi?', type:'article', bodyHtml:`<b>Enim</b> elit adipisicing amet irure cillum est laborum cupidatat officia ipsum minim nostrud amet fugiat. Nisi voluptate ex do veniam occaecat. Proident amet duis consequat eiusmod amet anim ex ullamco labore Lorem eiusmod.`},
        {id:41, title:'Da li tek rođene bebe treba kupati svake večeri?', type:'article', bodyHtml:`<b>Cupidatat</b> eu sint deserunt elit. Magna ex enim occaecat sit mollit officia ut dolor ipsum amet est qui reprehenderit consectetur. Est proident aliqua consequat consequat laboris.`},
    ],
};

export const listCardFaqSearchResultsDummyData: Props = {
    title: 'Najčešća Pitanja',
    subTitle: '8 Rezultata',
    items: [
        {id:1, title:'Kada najranije možemo da kupamo bebu u ležećem položaju u kadici?', type:'faq', bodyHtml:`<b>Adipisicing</b> in nulla cillum ex amet minim anim ad sit ut duis. Non reprehenderit proident magna mollit do fugiat excepteur tempor in minim nulla incididunt reprehenderit magna. Eiusmod aliqua exercitation non irure tempor.`},
        {id:2, title:'Koliko dugo beba sme da se kupa u kadi?', type:'faq', bodyHtml:`<b>Fugiat</b> id nulla deserunt nisi velit ea ut tempor fugiat reprehenderit culpa non nisi. Incididunt laboris officia laboris et exercitation ex deserunt ullamco. Ex pariatur dolore nulla elit occaecat laborum dolore irure irure cupidatat ea non non qui. Aliquip ipsum veniam enim ut mollit non aliquip non. Amet adipisicing minim commodo ex fugiat sit id elit fugiat voluptate consectetur.`},
        {id:3, title:'Da li tek rođene bebe treba kupati svake večeri?', type:'faq', bodyHtml:`<b>Occaecat</b> sunt velit dolor dolor duis consequat officia eiusmod sint. Deserunt adipisicing exercitation eu minim mollit nulla adipisicing ad velit. Esse occaecat Lorem tempor id irure ullamco ad irure dolore duis velit quis fugiat commodo. Laboris laboris aliquip eu aliqua non minim aute veniam. Et consectetur deserunt exercitation aliquip consectetur veniam.`},
        {id:4, title:'Da li koristiti sapun?', type:'faq', bodyHtml:`<b>Velit</b> pariatur reprehenderit aliqua anim eu quis voluptate laboris ipsum. Aliqua pariatur elit irure cupidatat cillum incididunt ea minim nostrud non aliqua. Quis do officia labore ipsum laborum. Cillum laboris et proident commodo velit laboris labore et nulla culpa. Magna enim dolore duis fugiat. Do id aute ex sint aliquip dolor et.`},
        {id:5, title:'Da li koristiti sunđer?', type:'faq', bodyHtml:`<b>Esse</b> culpa minim mollit laborum. Aute enim eiusmod laborum ex sunt laborum veniam dolor nisi est. Id incididunt fugiat magna sint ea amet. Ad fugiat cupidatat sunt enim enim excepteur deserunt pariatur ex pariatur minim deserunt nulla velit.`},
        {id:6, title:'Kada najranije možemo da kupamo bebu u ležećem položaju u kadici?', type:'faq', bodyHtml:`<b>Quis</b> id eu nulla anim exercitation aute nisi. Duis aliquip qui enim reprehenderit do qui nulla ad consequat sint enim. Proident commodo occaecat voluptate proident ex cupidatat deserunt esse adipisicing qui. Minim do deserunt non enim consequat tempor aliquip labore qui amet sunt. Ea nisi proident incididunt velit.`},
        {id:7, title:'Koliko dugo beba sme da se kupa u kadi?', type:'faq', bodyHtml:`<b>Enim</b> elit adipisicing amet irure cillum est laborum cupidatat officia ipsum minim nostrud amet fugiat. Nisi voluptate ex do veniam occaecat. Proident amet duis consequat eiusmod amet anim ex ullamco labore Lorem eiusmod.`},
        {id:8, title:'Da li tek rođene bebe treba kupati svake večeri?', type:'faq', bodyHtml:`<b>Cupidatat</b> eu sint deserunt elit. Magna ex enim occaecat sit mollit officia ut dolor ipsum amet est qui reprehenderit consectetur. Est proident aliqua consequat consequat laboris.`},
    ],
};

export const listCardFaqYourChildDummyData: Props = {
    title: 'Vaše dete',
    items: [
        {id:1, title:'Ishrana i dojenje', type:'faq', bodyHtml:`<b>Adipisicing</b> in nulla cillum ex amet minim anim ad sit ut duis. Non reprehenderit proident magna mollit do fugiat excepteur tempor in minim nulla incididunt reprehenderit magna. Eiusmod aliqua exercitation non irure tempor.`},
        {id:2, title:'Detetovo zdravlje', type:'faq', bodyHtml:`<b>Fugiat</b> id nulla deserunt nisi velit ea ut tempor fugiat reprehenderit culpa non nisi. Incididunt laboris officia laboris et exercitation ex deserunt ullamco. Ex pariatur dolore nulla elit occaecat laborum dolore irure irure cupidatat ea non non qui. Aliquip ipsum veniam enim ut mollit non aliquip non. Amet adipisicing minim commodo ex fugiat sit id elit fugiat voluptate consectetur.`},
        {id:3, title:'Nega i higijena', type:'faq', bodyHtml:`<b>Occaecat</b> sunt velit dolor dolor duis consequat officia eiusmod sint. Deserunt adipisicing exercitation eu minim mollit nulla adipisicing ad velit. Esse occaecat Lorem tempor id irure ullamco ad irure dolore duis velit quis fugiat commodo. Laboris laboris aliquip eu aliqua non minim aute veniam. Et consectetur deserunt exercitation aliquip consectetur veniam.`},
        {id:4, title:'Igra i komunikacija', type:'faq', bodyHtml:`<b>Velit</b> pariatur reprehenderit aliqua anim eu quis voluptate laboris ipsum. Aliqua pariatur elit irure cupidatat cillum incididunt ea minim nostrud non aliqua. Quis do officia labore ipsum laborum. Cillum laboris et proident commodo velit laboris labore et nulla culpa. Magna enim dolore duis fugiat. Do id aute ex sint aliquip dolor et.`},
        {id:5, title:'Rast i razvoj', type:'faq', bodyHtml:`<b>Esse</b> culpa minim mollit laborum. Aute enim eiusmod laborum ex sunt laborum veniam dolor nisi est. Id incididunt fugiat magna sint ea amet. Ad fugiat cupidatat sunt enim enim excepteur deserunt pariatur ex pariatur minim deserunt nulla velit.`},
    ],
};

export const listCardFaqPerAgeDummyData: Props = {
    title: 'Po uzrastu',
    items: [
        {id:1, title:'0 - 3 meseca', type:'faq', bodyHtml:`<b>Adipisicing</b> in nulla cillum ex amet minim anim ad sit ut duis. Non reprehenderit proident magna mollit do fugiat excepteur tempor in minim nulla incididunt reprehenderit magna. Eiusmod aliqua exercitation non irure tempor.`},
        {id:2, title:'3 - 6 meseci', type:'faq', bodyHtml:`<b>Fugiat</b> id nulla deserunt nisi velit ea ut tempor fugiat reprehenderit culpa non nisi. Incididunt laboris officia laboris et exercitation ex deserunt ullamco. Ex pariatur dolore nulla elit occaecat laborum dolore irure irure cupidatat ea non non qui. Aliquip ipsum veniam enim ut mollit non aliquip non. Amet adipisicing minim commodo ex fugiat sit id elit fugiat voluptate consectetur.`},
        {id:3, title:'6 - 8 meseci', type:'faq', bodyHtml:`<b>Occaecat</b> sunt velit dolor dolor duis consequat officia eiusmod sint. Deserunt adipisicing exercitation eu minim mollit nulla adipisicing ad velit. Esse occaecat Lorem tempor id irure ullamco ad irure dolore duis velit quis fugiat commodo. Laboris laboris aliquip eu aliqua non minim aute veniam. Et consectetur deserunt exercitation aliquip consectetur veniam.`},
        {id:4, title:'Ishrana u prva 3 meseca', type:'faq', bodyHtml:`<b>Velit</b> pariatur reprehenderit aliqua anim eu quis voluptate laboris ipsum. Aliqua pariatur elit irure cupidatat cillum incididunt ea minim nostrud non aliqua. Quis do officia labore ipsum laborum. Cillum laboris et proident commodo velit laboris labore et nulla culpa. Magna enim dolore duis fugiat. Do id aute ex sint aliquip dolor et.`},
        {id:5, title:'Razvoj u prvoj godini', type:'faq', bodyHtml:`<b>Esse</b> culpa minim mollit laborum. Aute enim eiusmod laborum ex sunt laborum veniam dolor nisi est. Id incididunt fugiat magna sint ea amet. Ad fugiat cupidatat sunt enim enim excepteur deserunt pariatur ex pariatur minim deserunt nulla velit.`},
    ],
};

export const listCardFaqMamaDummyData: Props = {
    title: 'Mama',
    items: [
        {id:1, title:'Trudnoca', type:'faq', bodyHtml:`<b>Adipisicing</b> in nulla cillum ex amet minim anim ad sit ut duis. Non reprehenderit proident magna mollit do fugiat excepteur tempor in minim nulla incididunt reprehenderit magna. Eiusmod aliqua exercitation non irure tempor.`},
        {id:2, title:'Porodjaj', type:'faq', bodyHtml:`<b>Fugiat</b> id nulla deserunt nisi velit ea ut tempor fugiat reprehenderit culpa non nisi. Incididunt laboris officia laboris et exercitation ex deserunt ullamco. Ex pariatur dolore nulla elit occaecat laborum dolore irure irure cupidatat ea non non qui. Aliquip ipsum veniam enim ut mollit non aliquip non. Amet adipisicing minim commodo ex fugiat sit id elit fugiat voluptate consectetur.`},
        {id:3, title:'Mamino zdravlje posle porodjaja', type:'faq', bodyHtml:`<b>Occaecat</b> sunt velit dolor dolor duis consequat officia eiusmod sint. Deserunt adipisicing exercitation eu minim mollit nulla adipisicing ad velit. Esse occaecat Lorem tempor id irure ullamco ad irure dolore duis velit quis fugiat commodo. Laboris laboris aliquip eu aliqua non minim aute veniam. Et consectetur deserunt exercitation aliquip consectetur veniam.`},
        {id:4, title:'Ishrana i dojenje', type:'faq', bodyHtml:`<b>Velit</b> pariatur reprehenderit aliqua anim eu quis voluptate laboris ipsum. Aliqua pariatur elit irure cupidatat cillum incididunt ea minim nostrud non aliqua. Quis do officia labore ipsum laborum. Cillum laboris et proident commodo velit laboris labore et nulla culpa. Magna enim dolore duis fugiat. Do id aute ex sint aliquip dolor et.`},
        {id:5, title:'Uloga majke u porodici', type:'faq', bodyHtml:`<b>Esse</b> culpa minim mollit laborum. Aute enim eiusmod laborum ex sunt laborum veniam dolor nisi est. Id incididunt fugiat magna sint ea amet. Ad fugiat cupidatat sunt enim enim excepteur deserunt pariatur ex pariatur minim deserunt nulla velit.`},
    ],
};

export const listCardFaqDummyData: Props = {
    items: [
        {id:1, title:'Dojim svoju bebu. Da li je potrebno da joj dajem i vodu?', type:'faq', bodyHtml:`<b>Adipisicing</b> in nulla cillum ex amet minim anim ad sit ut duis. Non reprehenderit proident magna mollit do fugiat excepteur tempor in minim nulla incididunt reprehenderit magna. Eiusmod aliqua exercitation non irure tempor.`},
        {id:2, title:'Da li adaptirano mleko mogu da pripremam sa prokuvanom prohlađenom vodom sa česme?', type:'faq', bodyHtml:`<b>Fugiat</b> id nulla deserunt nisi velit ea ut tempor fugiat reprehenderit culpa non nisi. Incididunt laboris officia laboris et exercitation ex deserunt ullamco. Ex pariatur dolore nulla elit occaecat laborum dolore irure irure cupidatat ea non non qui. Aliquip ipsum veniam enim ut mollit non aliquip non. Amet adipisicing minim commodo ex fugiat sit id elit fugiat voluptate consectetur.`},
        {id:3, title:'Dojim svoju bebu već šest meseci i planiram polako da joj uvedem i čvrstu hranu. Da li je moje mleko dovoljna tečnost za bebu ili ipak treba da joj dodam i vodu?', type:'faq', bodyHtml:`<b>Occaecat</b> sunt velit dolor dolor duis consequat officia eiusmod sint. Deserunt adipisicing exercitation eu minim mollit nulla adipisicing ad velit. Esse occaecat Lorem tempor id irure ullamco ad irure dolore duis velit quis fugiat commodo. Laboris laboris aliquip eu aliqua non minim aute veniam. Et consectetur deserunt exercitation aliquip consectetur veniam.`},
        {id:4, title:'Kako da znam da mojoj tromesečnoj bebi nedostaje tečnost i šta da radim ako jeste?', type:'faq', bodyHtml:`<b>Velit</b> pariatur reprehenderit aliqua anim eu quis voluptate laboris ipsum. Aliqua pariatur elit irure cupidatat cillum incididunt ea minim nostrud non aliqua. Quis do officia labore ipsum laborum. Cillum laboris et proident commodo velit laboris labore et nulla culpa. Magna enim dolore duis fugiat. Do id aute ex sint aliquip dolor et.`},
        {id:5, title:'Moja desetomesečna beba povraća ima visoku temperaturu i proliv. Šta da radim?', type:'faq', bodyHtml:`<b>Esse</b> culpa minim mollit laborum. Aute enim eiusmod laborum ex sunt laborum veniam dolor nisi est. Id incididunt fugiat magna sint ea amet. Ad fugiat cupidatat sunt enim enim excepteur deserunt pariatur ex pariatur minim deserunt nulla velit.`},
        {id:6, title:'Dojim svoju bebu. Da li je potrebno da joj dajem i vodu?', type:'faq', bodyHtml:`<b>Adipisicing</b> in nulla cillum ex amet minim anim ad sit ut duis. Non reprehenderit proident magna mollit do fugiat excepteur tempor in minim nulla incididunt reprehenderit magna. Eiusmod aliqua exercitation non irure tempor.`},
        {id:7, title:'Da li adaptirano mleko mogu da pripremam sa prokuvanom prohlađenom vodom sa česme?', type:'faq', bodyHtml:`<b>Fugiat</b> id nulla deserunt nisi velit ea ut tempor fugiat reprehenderit culpa non nisi. Incididunt laboris officia laboris et exercitation ex deserunt ullamco. Ex pariatur dolore nulla elit occaecat laborum dolore irure irure cupidatat ea non non qui. Aliquip ipsum veniam enim ut mollit non aliquip non. Amet adipisicing minim commodo ex fugiat sit id elit fugiat voluptate consectetur.`},
        {id:8, title:'Dojim svoju bebu već šest meseci i planiram polako da joj uvedem i čvrstu hranu. Da li je moje mleko dovoljna tečnost za bebu ili ipak treba da joj dodam i vodu?', type:'faq', bodyHtml:`<b>Occaecat</b> sunt velit dolor dolor duis consequat officia eiusmod sint. Deserunt adipisicing exercitation eu minim mollit nulla adipisicing ad velit. Esse occaecat Lorem tempor id irure ullamco ad irure dolore duis velit quis fugiat commodo. Laboris laboris aliquip eu aliqua non minim aute veniam. Et consectetur deserunt exercitation aliquip consectetur veniam.`},
        {id:9, title:'Kako da znam da mojoj tromesečnoj bebi nedostaje tečnost i šta da radim ako jeste?', type:'faq', bodyHtml:`<b>Velit</b> pariatur reprehenderit aliqua anim eu quis voluptate laboris ipsum. Aliqua pariatur elit irure cupidatat cillum incididunt ea minim nostrud non aliqua. Quis do officia labore ipsum laborum. Cillum laboris et proident commodo velit laboris labore et nulla culpa. Magna enim dolore duis fugiat. Do id aute ex sint aliquip dolor et.`},
        {id:10, title:'Moja desetomesečna beba povraća ima visoku temperaturu i proliv. Šta da radim?', type:'faq', bodyHtml:`<b>Esse</b> culpa minim mollit laborum. Aute enim eiusmod laborum ex sunt laborum veniam dolor nisi est. Id incididunt fugiat magna sint ea amet. Ad fugiat cupidatat sunt enim enim excepteur deserunt pariatur ex pariatur minim deserunt nulla velit.`},
    ],
};

// export const listCardFaqYourChildDummyData: Props = {
//     title: '',
//     subTitle: '8 Rezultata',
//     items: [
//         {id:1, title:'', type:'faq', bodyHtml:`<b>Adipisicing</b> in nulla cillum ex amet minim anim ad sit ut duis. Non reprehenderit proident magna mollit do fugiat excepteur tempor in minim nulla incididunt reprehenderit magna. Eiusmod aliqua exercitation non irure tempor.`},
//         {id:2, title:'', type:'faq', bodyHtml:`<b>Fugiat</b> id nulla deserunt nisi velit ea ut tempor fugiat reprehenderit culpa non nisi. Incididunt laboris officia laboris et exercitation ex deserunt ullamco. Ex pariatur dolore nulla elit occaecat laborum dolore irure irure cupidatat ea non non qui. Aliquip ipsum veniam enim ut mollit non aliquip non. Amet adipisicing minim commodo ex fugiat sit id elit fugiat voluptate consectetur.`},
//         {id:3, title:'', type:'faq', bodyHtml:`<b>Occaecat</b> sunt velit dolor dolor duis consequat officia eiusmod sint. Deserunt adipisicing exercitation eu minim mollit nulla adipisicing ad velit. Esse occaecat Lorem tempor id irure ullamco ad irure dolore duis velit quis fugiat commodo. Laboris laboris aliquip eu aliqua non minim aute veniam. Et consectetur deserunt exercitation aliquip consectetur veniam.`},
//         {id:4, title:'', type:'faq', bodyHtml:`<b>Velit</b> pariatur reprehenderit aliqua anim eu quis voluptate laboris ipsum. Aliqua pariatur elit irure cupidatat cillum incididunt ea minim nostrud non aliqua. Quis do officia labore ipsum laborum. Cillum laboris et proident commodo velit laboris labore et nulla culpa. Magna enim dolore duis fugiat. Do id aute ex sint aliquip dolor et.`},
//         {id:5, title:'', type:'faq', bodyHtml:`<b>Esse</b> culpa minim mollit laborum. Aute enim eiusmod laborum ex sunt laborum veniam dolor nisi est. Id incididunt fugiat magna sint ea amet. Ad fugiat cupidatat sunt enim enim excepteur deserunt pariatur ex pariatur minim deserunt nulla velit.`},
//         {id:6, title:'', type:'faq', bodyHtml:`<b>Quis</b> id eu nulla anim exercitation aute nisi. Duis aliquip qui enim reprehenderit do qui nulla ad consequat sint enim. Proident commodo occaecat voluptate proident ex cupidatat deserunt esse adipisicing qui. Minim do deserunt non enim consequat tempor aliquip labore qui amet sunt. Ea nisi proident incididunt velit.`},
//         {id:7, title:'', type:'faq', bodyHtml:`<b>Enim</b> elit adipisicing amet irure cillum est laborum cupidatat officia ipsum minim nostrud amet fugiat. Nisi voluptate ex do veniam occaecat. Proident amet duis consequat eiusmod amet anim ex ullamco labore Lorem eiusmod.`},
//         {id:8, title:'', type:'faq', bodyHtml:`<b>Cupidatat</b> eu sint deserunt elit. Magna ex enim occaecat sit mollit officia ut dolor ipsum amet est qui reprehenderit consectetur. Est proident aliqua consequat consequat laboris.`},
//     ],
// };